const problem = [
  {
    1672: "https://leetcode.com/problems/richest-customer-wealth/",
    1295: "https://leetcode.com/problems/find-numbers-with-even-number-of-digits/",
    744: "https://leetcode.com/problems/find-smallest-letter-greater-than-target/",
    34: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
    852: "https://leetcode.com/problems/peak-index-in-a-mountain-array/",
    1095: "https://leetcode.com/problems/find-in-mountain-array/",
    162: "https://leetcode.com/problems/find-peak-element/description/",
    410: "https://leetcode.com/problems/split-array-largest-sum/",
    268: "https://leetcode.com/problems/missing-number/",
    448: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/description/",
    287: "https://leetcode.com/problems/find-the-duplicate-number/",
    442: "https://leetcode.com/problems/find-all-duplicates-in-an-array/",
    645: "https://leetcode.com/problems/set-mismatch/submissions/",
    41: "https://leetcode.com/problems/first-missing-positive/submissions/",
    832: "https://leetcode.com/problems/flipping-an-image/description/",
    215: "https://leetcode.com/problems/kth-largest-element-in-an-array/description/",
    983: "https://leetcode.com/problems/minimum-cost-for-tickets/description/",
    1039: "https://leetcode.com/problems/minimum-score-triangulation-of-polygon/description/",
    1402: "https://leetcode.com/problems/reducing-dishes/description/",
  },
];
